EVENTOS_ESPECIAIS = {
    "Pewter City": "Brock",
    "Cerulean City": "Misty",
    "Vermilion City": "Lt. Surge",
    "Celadon City": "Erika",
    "Fuchsia City": "Koga",
    "Saffron City": "Sabrina",
    "Cinnabar Island": "Blaine",
    "Viridian City": "Giovanni",
    "Indigo Plateau": "Elite Four"
}

POKEMONS_INICIAIS = ["Bulbasaur", "Charmander", "Squirtle"]

POKEMONS_POR_ROTA = {
    "Pallet Town": ["Bulbasaur", "Charmander", "Squirtle", "Poliwag", "Tentacool"],
    "Route 1": ["Pidgey", "Rattata"],
    "Viridian City": ["Poliwag", "Tentacool"],
    "Route 2": ["Caterpie", "Weedle", "Pidgey", "Rattata", "Mr. Mime"],
    "Viridian Forest": ["Caterpie", "Metapod", "Weedle", "Kakuna", "Pikachu"],
    "Route 3": ["Pidgey", "Spearow", "Jigglypuff", "Magikarp"],
    "Mt. Moon": ["Zubat", "Paras", "Geodude", "Clefairy"],
    "Route 4": ["Rattata", "Spearow", "Ekans", "Psyduck", "Krabby", "Goldeen"],
    "Cerulean City": ["Psyduck", "Poliwag", "Krabby", "Goldeen", "Jynx"],
    "Route 24": ["Caterpie", "Metapod", "Weedle", "Kakuna",
                 "Pidgey", "Oddish", "Venonat", "Psyduck", "Abra", "Goldeen"],
    "Route 25": ["Caterpie", "Metapod", "Weedle", "Kakuna",
                 "Pidgey", "Oddish", "Venonat", "Psyduck", "Abra", "Goldeen"],
    "Route 5": ["Pidgey", "Oddish", "Mankey"],
    "Route 6": ["Pidgey", "Oddish", "Mankey", "Shellder", "Krabby"],
    "Vermilion City": ["Poliwag", "Farfetch'd", "Shellder", "Krabby"],
    "Diglett's Cave": ["Diglett", "Dugtrio"],
    "Route 9": ["Rattata", "Spearow", "Ekans", "Poliwhirl", "Slowpoke", "Voltorb"],
    "Route 10": ["Slowpoke", "Zubat", "Machop", "Geodude", "Onix"],
    "Lavender Town": ["Gastly", "Haunter", "Cubone"],
    "Route 8": ["Pidgey", "Ekans", "Mankey", "Growlithe"],
    "Celadon City": ["Nidorina", "Nidorino", "Clefairy", "Poliwhirl",
                     "Abra", "Slowpoke", "Horsea", "Scyther", "Eevee", "Porygon", "Dratini"],
    "Saffron City": ["Hitmonlee", "Hitmonchan", "Lapras"],
    "Route 11": ["Spearow", "Ekans", "Nidorina", "Shellder", "Drowzee", "Krabby"],
    "Route 12": ["Pidgey", "Oddish", "Gloom", "Venonat", "Tentacool", "Krabby", "Goldeen", "Magikarp", "Snorlax"],
    "Route 13": ["Pidgey", "Oddish", "Gloom", "Venonat", "Tentacool", "Krabby", "Goldeen", "Magikarp", "Ditto"],
    "Route 14": ["Pidgey", "Pidgeotto", "Rattata", "Oddish", "Gloom",
                 "Venonat", "Krabby", "Ditto"],
    "Route 15": ["Pidgey", "Pidgeotto", "Rattata", "Oddish", "Gloom",
                 "Venonat", "Krabby", "Ditto"],
    "Route 16": ["Rattata", "Raticate", "Spearow", "Doduo", "Snorlax"],
    "Route 17": ["Raticate", "Spearow", "Fearow", "Doduo", "Krabby", "Goldeen", "Magikarp"],
    "Route 18": ["Rattata", "Raticate", "Spearow", "Fearow", "Doduo",
                 "Krabby", "Lickitung", "Goldeen", "Magikarp"],
    "Fuchsia City": ["Krabby", "Goldeen", "Seaking", "Magikarp"],
    "Safari Zone": ["Nidoran♀", "Nidorina", "Nidoran♂", "Nidorino",
                    "Paras", "Parasect", "Venonat", "Venomoth", "Psyduck",
                    "Slowpoke", "Doduo", "Krabby", "Exeggcute",
                    "Rhyhorn", "Chansey", "Kangaskhan", "Scyther",
                    "Tauros", "Dratini", "Dragonair"],
    "Power Plant": ["Pikachu", "Raichu", "Magnemite", "Magneton", "Voltorb", "Electrode", "Electabuzz", "Zapdos"],
    "Sea Route 19": ["Poliwhirl", "Tentacool", "Shellder", "Horsea", "Goldeen", "Staryu"],
    "Sea Route 20": ["Tentacool", "Shellder", "Horsea", "Goldeen", "Staryu"],
    "Cinnabar Island": ["Growlithe", "Ponyta", "Slowpoke", "Seel", "Grimer",
                        "Muk", "Shellder", "Krabby", "Electrode", "Koffing", "Weezing",
                        "Tangela", "Horsea", "Goldeen", "Staryu",
                        "Omanyte", "Kabuto", "Aerodactyl"],
    "Sea Route 21": ["Pidgeotto", "Rattata", "Raticate", "Tentacool", "Shellder",
                     "Tangela", "Horsea", "Goldeen", "Staryu"],
    "Route 22": ["Rattata", "Spearow", "Nidoran♀", "Nidoran♂", "Poliwag", "Goldeen"],
    "Route 23": ["Spearow", "Fearow", "Ekans", "Arbok", "Raichu",
                 "Golbat", "Slowbro", "Kingler", "Seadra", "Seaking", "Ditto"],
    "Victory Road": ["Zubat", "Golbat", "Venomoth", "Machop", "Machoke",
                     "Geodude", "Graveler", "Onix", "Marowak", "Moltres"],
}

REQUISITOS_LOCAL = {
    "Pewter City": [],
    "Cerulean City": ["Brock"],
    "Vermilion City": ["Misty"],
    "Celadon City": ["Lt. Surge"],
    "Fuchsia City": ["Erika"],
    "Saffron City": ["Koga"],
    "Cinnabar Island": ["Sabrina"],
    "Viridian City": ["Blaine"],
    "Indigo Plateau": [
        "Brock", "Misty", "Lt. Surge", "Erika", "Koga", "Sabrina", "Blaine", "Giovanni"
    ]
}

EFICACIA_TIPOS = {
    ("Fogo", "Planta"): 2.0,
    ("Fogo", "Inseto"): 2.0,
    ("Fogo", "Gelo"): 2.0,
    ("Fogo", "Água"): 0.5,
    ("Fogo", "Rocha"): 0.5,
    ("Fogo", "Fogo"): 0.5,

    ("Água", "Fogo"): 2.0,
    ("Água", "Rocha"): 2.0,
    ("Água", "Terra"): 2.0,
    ("Água", "Água"): 0.5,
    ("Água", "Grama"): 0.5,

    ("Grama", "Água"): 2.0,
    ("Grama", "Rocha"): 2.0,
    ("Grama", "Terra"): 2.0,
    ("Grama", "Fogo"): 0.5,
    ("Grama", "Grama"): 0.5,
    ("Grama", "Venenoso"): 0.5,
    ("Grama", "Inseto"): 0.5,
    ("Grama", "Voador"): 0.5,

    ("Elétrico", "Água"): 2.0,
    ("Elétrico", "Voador"): 2.0,
    ("Elétrico", "Elétrico"): 0.5,
    ("Elétrico", "Grama"): 0.5,
    ("Elétrico", "Terra"): 0.0,

    ("Normal", "Rocha"): 0.5,
    ("Normal", "Fantasma"): 0.0,

    ("Lutador", "Normal"): 2.0,
    ("Lutador", "Rocha"): 2.0,
    ("Lutador", "Gelo"): 2.0,
    ("Lutador", "Voador"): 0.5,
    ("Lutador", "Venenoso"): 0.5,
    ("Lutador", "Psíquico"): 0.5,
    ("Lutador", "Inseto"): 0.5,
    ("Lutador", "Fantasma"): 0.0,

    ("Venenoso", "Grama"): 2.0,
    ("Venenoso", "Venenoso"): 0.5,
    ("Venenoso", "Terra"): 0.5,
    ("Venenoso", "Rocha"): 0.5,
    ("Venenoso", "Fantasma"): 0.5,

    ("Terra", "Fogo"): 2.0,
    ("Terra", "Elétrico"): 2.0,
    ("Terra", "Rocha"): 2.0,
    ("Terra", "Grama"): 0.5,
    ("Terra", "Inseto"): 0.5,
    ("Terra", "Voador"): 0.0,

    ("Psíquico", "Lutador"): 2.0,
    ("Psíquico", "Venenoso"): 2.0,
    ("Psíquico", "Psíquico"): 0.5,

    ("Inseto", "Grama"): 2.0,
    ("Inseto", "Psíquico"): 2.0,
    ("Inseto", "Venenoso"): 2.0,
    ("Inseto", "Fogo"): 0.5,
    ("Inseto", "Lutador"): 0.5,
    ("Inseto", "Voador"): 0.5,
    ("Inseto", "Fantasma"): 0.5,

    ("Rocha", "Fogo"): 2.0,
    ("Rocha", "Gelo"): 2.0,
    ("Rocha", "Voador"): 2.0,
    ("Rocha", "Inseto"): 2.0,
    ("Rocha", "Lutador"): 0.5,
    ("Rocha", "Terra"): 0.5,

    ("Fantasma", "Fantasma"): 2.0,
    ("Fantasma", "Normal"): 0.0,
    ("Fantasma", "Psíquico"): 0.0,

    ("Gelo", "Grama"): 2.0,
    ("Gelo", "Terra"): 2.0,
    ("Gelo", "Voador"): 2.0,
    ("Gelo", "Dragão"): 2.0,
    ("Gelo", "Fogo"): 0.5,
    ("Gelo", "Água"): 0.5,

    ("Dragão", "Dragão"): 2.0,
}